Hw09 struct validator
adrianoff/golang-otus-homeworks pull request #10
Opened 2024-02-26 11:42 UTC by adrianoff

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-02-27 05:54 UTC, vladislavmass requested changes

2024-02-27 05:54 UTC, vladislavmass commented on hw09_struct_validator/validators/inValidator.go
> +func InValidator(inValues string, v reflect.Value) error {
Валидатор in должен работать в том числе и со слайсами

2024-02-27 05:54 UTC, vladislavmass commented on hw09_struct_validator/validators/lenValidator.go
> +		for _, val := range v.Interface().([]string) {
А что будет если сюда придет слайс интов?

2024-02-27 05:54 UTC, vladislavmass commented on hw09_struct_validator/validators/maxValidator.go
> +		for _, val := range v.Interface().([]int) {
Что будет если сюда придет слайс стрингов?

2024-02-29 15:11 UTC, adrianoff commented on hw09_struct_validator/validators/lenValidator.go
> +		for _, val := range v.Interface().([]string) {
Не получается решить проблему. Как определить какой тип лежит в слайсе reflect.Value Подскажите, пожалуйста, как бы вы решили?

2024-03-01 10:36 UTC, adrianoff commented on hw09_struct_validator/validators/lenValidator.go
> +		for _, val := range v.Interface().([]string) {
@vladislavmass ?

2024-03-04 13:42 UTC, vladislavmass approved these changes

2024-08-08 22:08 UTC, merged